#!/usr/bin/php
<?php

// ---------
// Config
// ---------

$host = 'openphoto.adrien-gallou.fr';

include 'api-php/OpenPhotoOAuth.php';
include 'src/syncLogger.class.php';
include 'src/functions.php';

// ---------
// Config
// ---------

$consumerKey    = getenv('consumerKey');
$consumerSecret = getenv('consumerSecret');
$token          = getenv('token');
$tokenSecret    = getenv('tokenSecret');

// ---------
// Execution
// ---------

$dir    = $argv[1];
$client = new OpenPhotoOAuth($host, $consumerKey, $consumerSecret, $token, $tokenSecret);
$logger = new syncLogger();
$hashs  = getHashs($client);
$paths  = getPaths($dir);
$logger->log(sprintf('%s photos on openphoto', count($hashs)));

foreach ($paths as $pathName)
{
  uploadFile($client, $logger, $hashs, $pathName);
}

$newHashs = getHashs($client);
$logger->log(sprintf('%s photos added', count($newHashs) - count($hashs)));
$logger->log(sprintf('%s photos now on openphoto', count($hashs)));

