#!/usr/bin/php
<?php

include 'vendor/api-php/OpenPhotoOAuth.php';
include 'src/syncLogger.class.php';
include 'src/functions.php';
include 'config/config.php';

$dir    = $argv[1];
$client = new OpenPhotoOAuth($config['host'], $config['consumer_key'], $config['consumer_secret'], $config['token'], $config['token_secret']);
$logger = new syncLogger();
$hashs  = getHashs($client);
$paths  = getPaths($dir);
$logger->log(sprintf('%s photos on openphoto', count($hashs)));

foreach ($paths as $pathName)
{
  uploadFile($client, $logger, $config['exiftran'], $hashs, $pathName);
}

$newHashs = getHashs($client);
$logger->log(sprintf('%s photos added', count($newHashs) - count($hashs)));
$logger->log(sprintf('%s photos now on openphoto', count($hashs)));
